const sb=(SUPABASE_URL&&SUPABASE_ANON_KEY)?supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const auth=document.getElementById("auth"),app=document.getElementById("app"),content=document.getElementById("content"),msg=document.getElementById("msg");
function k(icon,label,value,trend,accent,soft){return `<div class="kpi" style="--accent:${accent};--soft:${soft}"><div class="kicon">${icon}</div><h2>${value}</h2><div class="up">↑ ${trend} <small>vs last term</small></div><div class="spark"></div><small>${label}</small></div>`}
function activity(i,t,d,time){return `<div class="activity"><div class="bubble">${i}</div><div><b>${t}</b><span>${d}</span></div><span class="time">${time}</span></div>`}
function event(day,mon,t,s){return `<div class="event"><div class="date"><small>${mon}</small><b>${day}</b></div><div><b>${t}</b><span>${s}</span></div></div>`}
function dashboard(){content.innerHTML=`<div class="welcome"><div><h1>Good morning, Vincent 👋</h1><p>A clear view of today's school operations, academics and finances.</p></div><div class="term"><b>Monday, 28 April 2025</b><small>Academic Year 2024–2025　•　Term 2</small></div></div>
<div class="banner"><h2>Learning today. Leading tomorrow.</h2><p>One workspace for your entire school.</p></div>
<div class="kpis">${k("♙","Total Students","1,248","+12%","#2477ef","#edf5ff")}${k("♟","Total Staff","86","+5%","#7b50ed","#f2edff")}${k("▦","Total Classes","32","+8%","#10aa7c","#e9fbf5")}${k("▤","Total Subjects","48","+10%","#f39a18","#fff5e5")}${k("₵","Fees Collected","UGX 12,450,000","+18%","#e94d7b","#fff0f5")}</div>
<div class="rows"><div class="card"><div class="head"><b>Student Enrollment</b><span>Last 6 months⌄</span></div><div class="chart"><div class="line"></div><svg viewBox="0 0 600 160" preserveAspectRatio="none"><path d="M0 135 C90 125 95 108 190 116 S290 88 385 94 S490 68 600 35" fill="none" stroke="#2677ef" stroke-width="3"/><path d="M0 135 C90 125 95 108 190 116 S290 88 385 94 S490 68 600 35 L600 160 L0 160Z" fill="#2677ef" opacity=".08"/></svg><div class="axis"><span>Nov</span><span>Dec</span><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span></div></div></div>
<div class="card"><div class="head"><b>Students by Class</b><span>View details →</span></div><div class="donutbox"><div class="donut"></div><div class="legend"><div><i class="dot" style="background:#2778ef"></i>Primary 1–3　31%</div><div><i class="dot" style="background:#1dbb91"></i>Primary 4–6　23%</div><div><i class="dot" style="background:#ffb331"></i>JSS 1–3　19%</div><div><i class="dot" style="background:#8754ee"></i>SSS 1–3　16%</div><div><i class="dot" style="background:#ef5b8d"></i>Other　11%</div></div></div></div>
<div class="card actions-card"><div class="head"><b>Quick actions</b><span>Shortcuts</span></div><div class="actions"><button class="action" data-page="students">♙<b>Add student</b></button><button class="action" data-page="staff">♟<b>Add staff</b></button><button class="action" data-page="attendance">✓<b>Record attendance</b></button><button class="action" data-page="fees">₵<b>Record payment</b></button><button class="action" data-page="exams">▤<b>Create examination</b></button><button class="action" data-page="reports">⌁<b>Generate report</b></button></div></div></div>
<div class="lower"><div class="card"><div class="head"><b>Recent activity</b><span>View all →</span></div>${activity("♙","New student admitted","Sarah N. — S.1","2 hrs ago")}${activity("₵","Fee payment received","UGX 250,000 — Term 2","3 hrs ago")}${activity("▤","Exam result published","Mathematics — S.3","5 hrs ago")}${activity("♧","New parent registered","Mr. & Mrs. Kato","7 hrs ago")}</div>
<div class="card"><div class="head"><b>Fee collection</b><span>This term⌄</span></div><div class="fee"><div class="ring"><b>72%</b></div><div><p>Collected amount</p><strong>UGX 12,450,000</strong><p style="margin-top:12px">Expected amount</p><strong>UGX 17,300,000</strong></div></div></div>
<div class="card calendar"><div class="head"><b>School calendar</b><span>Full calendar →</span></div>${event("30","APR","Parent–Teacher Meeting","9:00 AM – 12:00 PM")}${event("05","MAY","Term 2 Exams Begin","All classes")}${event("12","MAY","Staff Training","9:00 AM – 3:00 PM")}${event("20","MAY","School Holiday","All day")}</div></div>`}
const pages={students:["Students","Register, search and manage learner records."],parents:["Parents & Guardians","Manage parent contacts and learner relationships."],staff:["Staff & Teachers","Manage staff profiles, roles and departments."],classes:["Classes & Subjects","Organise classes, streams and teaching subjects."],attendance:["Attendance","Record and review daily attendance."],timetable:["Timetable","Build and manage class timetables."],exams:["Examinations","Create exams, enter marks and publish results."],reports:["Report Cards","Generate academic and administrative reports."],fees:["Fees & Payments","Track school fees, balances and receipts."],expenses:["Expenses","Record and monitor school expenditure."],budget:["Budget","Plan and monitor school budgets."],messages:["Messages","School announcements and communication."],settings:["School Settings","Configure school identity and system preferences."]};
function page(p){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="dashboard")return dashboard();let x=pages[p]||["Module","School management module"];content.innerHTML=`<div class="page"><div><h1>${x[0]}</h1><p>${x[1]}</p></div><button class="add">+ Add new</button></div><div class="placeholder"><b>${x[0]} module is ready for the next build stage</b><span>The responsive dashboard and Supabase foundation are in place. The full workflow will be added without changing this design.</span></div>`}
document.addEventListener("click",e=>{let b=e.target.closest("[data-page]");if(b){page(b.dataset.page);document.getElementById("side").classList.remove("open")}})
document.getElementById("mobile").onclick=()=>document.getElementById("side").classList.toggle("open");
document.getElementById("collapse").onclick=()=>document.getElementById("side").classList.toggle("collapsed");
document.getElementById("login").onsubmit=async e=>{e.preventDefault();msg.textContent="";if(!sb){msg.textContent="Add your Supabase URL and anon key in assets/js/config.js.";return}let {error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(error)msg.textContent=error.message;else show()};
document.getElementById("logout").onclick=async()=>{if(sb)await sb.auth.signOut();app.classList.add("hidden");auth.classList.remove("hidden")};
function show(){auth.classList.add("hidden");app.classList.remove("hidden");page("dashboard")}
if(sb)sb.auth.getSession().then(({data})=>{if(data.session)show()});
else show();
