const sb=(SUPABASE_URL&&SUPABASE_ANON_KEY)?supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const auth=document.getElementById('auth'),app=document.getElementById('app'),content=document.getElementById('content'),title=document.getElementById('title'),msg=document.getElementById('msg');
function openApp(){auth.classList.add('hidden');app.classList.remove('hidden');page('dashboard')}
function page(p){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));const names={dashboard:'Dashboard',students:'Students',staff:'Staff & Teachers',academics:'Academics',attendance:'Attendance',fees:'Fees & Finance',exams:'Examinations',reports:'Reports',settings:'School Settings'};title.textContent=names[p]||'Dashboard';
if(p==='dashboard')content.innerHTML=`<div class="welcome"><div><h1>Welcome back 👋</h1><p class="muted">School overview and quick actions.</p></div><button class="primary" onclick="page('students')">+ Register Student</button></div><div class="cards"><div class="card stat">👨‍🎓<strong>0</strong><span class="muted">Students</span></div><div class="card stat">👩‍🏫<strong>0</strong><span class="muted">Staff & Teachers</span></div><div class="card stat">🏫<strong>0</strong><span class="muted">Classes</span></div><div class="card stat">💰<strong>UGX 0</strong><span class="muted">Fees collected</span></div></div><div class="grid"><div class="card"><h3>Recent activity</h3><div class="empty">No activity yet.</div></div><div class="card"><h3>Quick actions</h3><p>Register students, add staff, configure academics and record payments.</p></div></div>`;
else {const desc={students:'Student registration, profiles, guardians and academic history.',staff:'Teachers and non-teaching staff records.',academics:'Classes, streams, subjects, academic years and terms.',attendance:'Daily student and staff attendance.',fees:'Fee structures, payments, receipts, balances and expenses.',exams:'Examinations, marks, grades and report cards.',reports:'Academic, attendance, student and financial reports.',settings:'School profile and system configuration.'}[p];content.innerHTML=`<div class="welcome"><div><h1>${names[p]}</h1><p class="muted">${desc}</p></div><button class="primary">Add New</button></div><div class="notice">This module is ready for the next development stage. The database foundation is included in this package.</div><div class="tiles"><div class="card tile"><h3>📋 Records</h3><p class="muted">Manage ${names[p].toLowerCase()} records.</p></div><div class="card tile"><h3>🔎 Search</h3><p class="muted">Find and filter records.</p></div><div class="card tile"><h3>📊 Reports</h3><p class="muted">View useful summaries and reports.</p></div></div>`}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{page(b.dataset.page);document.querySelector('aside').classList.remove('open')});
document.getElementById('menu').onclick=()=>document.querySelector('aside').classList.toggle('open');
document.getElementById('login').onsubmit=async e=>{e.preventDefault();msg.textContent='';if(!sb){msg.textContent='Add Supabase URL and key in assets/js/config.js first.';return}const {data,error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(error)msg.textContent=error.message;else openApp()};
document.getElementById('logout').onclick=async()=>{if(sb)await sb.auth.signOut();auth.classList.remove('hidden');app.classList.add('hidden')};
if(sb)sb.auth.getSession().then(({data})=>{if(data.session)openApp()});
